name: Nightly Release

on:
  schedule:
    - cron: '00 16 * * *' # GitHub Actions use UTC time

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.nightly-check.outputs.changes }}
    steps:
      - id: nightly-check
        name: Check for changes since the last nightly
        uses: lukecarr/nightly-check@v0.3.0
  nightly-release:
    needs: check
    if: ${{ needs.check.outputs.changes == 'true' }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      actions: read
    name: Create Nightly Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          branch: master

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Tiefsee Nightly Release $$'
          prerelease: true
          body: 'This is the Nightly version, compiled from the latest code committed to GitHub, and may be unstable.<br>此為 Nightly 版，以 GitHub 最新提交的程式碼編譯而成，可能存在不穩定。'
          files: |
            ./Tiefsee/Tiefsee.zip
